---
- name: Deploy Docker Container with Apache
  hosts: your_target_host
  become: yes
  tasks:
    - name: Install Docker if not already installed
      block:
        - name: Install required packages for Docker
          apt:
            name: "{{ item }}"
            state: present
          with_items:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
        - name: Add Docker's official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        - name: Install Docker
          apt:
            name: docker-ce docker-ce-cli containerd.io
            state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Pull Docker image for Apache
      docker_image:
        name: httpd:latest

    - name: Run Docker container for Apache
      docker_container:
        name: apache_container
        image: httpd:latest
        ports:
          - "80:80"
        volumes:
          - /path/to/your/webpage:/usr/local/apache2/htdocs
        restart_policy: always
